repos:
  - repo: https://github.com/packit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: validate-config # passes when packit not installed (e.g. in CI)
      - id: check-rebase
        args:
          - https://github.com/packit/packit.git
        stages: [manual, pre-push]
