# .github/workflows/packit-validate.yml
name: Validate Packit Config

on: [push, pull_request]

jobs:
  validate-packit:
    runs-on: ubuntu-latest

    container:
      image: fedora:rawhide

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install packit
        run: |
          dnf -y install packit

      - name: Validate Packit config
        run: |
          packit config validate
